// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5SFdVg1Cr4Ce7dU67FDFxRYd2On-sQGQ',
    appId: '1:267243047152:web:0bfa593c45197538fe9a35',
    messagingSenderId: '267243047152',
    projectId: 'hopeapp-900d0',
    authDomain: 'hopeapp-900d0.firebaseapp.com',
    databaseURL:
        'https://hopeapp-900d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hopeapp-900d0.appspot.com',
    measurementId: 'G-MKFF0T7GCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO_UnnPij_08a8iGBEQB8tMZdlFSelazI',
    appId: '1:267243047152:android:2a13d7d06e8ac991fe9a35',
    messagingSenderId: '267243047152',
    projectId: 'hopeapp-900d0',
    databaseURL:
        'https://hopeapp-900d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hopeapp-900d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR2qBZkG7PAn-Ifdb3y-0MB5S7O_wCTvc',
    appId: '1:267243047152:ios:ff45eb46261be67afe9a35',
    messagingSenderId: '267243047152',
    projectId: 'hopeapp-900d0',
    databaseURL:
        'https://hopeapp-900d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hopeapp-900d0.appspot.com',
    iosBundleId: 'com.example.hopeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR2qBZkG7PAn-Ifdb3y-0MB5S7O_wCTvc',
    appId: '1:267243047152:ios:ff45eb46261be67afe9a35',
    messagingSenderId: '267243047152',
    projectId: 'hopeapp-900d0',
    databaseURL:
        'https://hopeapp-900d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hopeapp-900d0.appspot.com',
    iosBundleId: 'com.example.hopeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5SFdVg1Cr4Ce7dU67FDFxRYd2On-sQGQ',
    appId: '1:267243047152:web:83b57316ca662131fe9a35',
    messagingSenderId: '267243047152',
    projectId: 'hopeapp-900d0',
    authDomain: 'hopeapp-900d0.firebaseapp.com',
    databaseURL:
        'https://hopeapp-900d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hopeapp-900d0.appspot.com',
    measurementId: 'G-WLEWQ12B7L',
  );
}
